In [15]:
import pandas as pd

df = pd.read_csv('sample.csv')

df['Average Price Per Person'] = df['Average Price Per Person'].astype(str)
df = df.drop(columns = ['Timestamp'])

df['Categories'] = df['Categories'].str.split(', ')
df2 = df.explode('Categories', ignore_index= False)

df_budget = df2.loc[(df2['Categories']== 'Beverages')]

# df2.loc[(df2['Name']=='Food Courtyard')]
df_budget

,Name,Categories,Average Price Per Person,Address,Google Link
0,Chai Sutta Bar,Beverages,100-150,"Laxmi Nagar , Sadar",https://www.google.com/search?q=chai+sutta+bar...
1,Chai Shai Bar,Beverages,100-150,Laxmi Nagar,https://www.google.com/search?sxsrf=ALiCzsaVy_...
6,"Cafe Coffee Day, Hotel Ashok",Beverages,300-600,Laxmi Nagar,https://www.google.com/search?gs_ssp=eJzj4tZP1...
7,House Of Caffeine,Beverages,300-600,"Laxmi Nagar, Hingna T-Point",https://www.google.com/search?q=house+of+caffe...
8,Tea Bar,Beverages,100-150,Laxmi Nagar,https://www.google.com/search?q=tea+bar+nagpur...
9,San Sebastian Cafe,Beverages,100-150,Laxmi Nagar Square,NaN
11,Brewin Cafe,Beverages,150-300,Laxmi Nagar,https://www.google.com/search?gs_ssp=eJzj4tVP1...
12,All That's Coffee,Beverages,100-150,"Pratap Nagar, Manish Nagar, Dharampeth, Wardha...",NaN
19,Villa 167,Beverages,300-600,Abhyankar Nagar,https://www.google.com/search?q=villa+167&oq=v...
20,Frullato,Beverages,100-150,"Bajaj Nagar, Sadar",NaN
21,Dessertino,Beverages,100-150,Bajaj Nagar,NaN
23,UFO - Fries & Corn,Beverages,150-300,Bajaj Nagar,https://www.google.com/search?sxsrf=ALiCzsaIhe...
27,The Chatori Street,Beverages,150-300,Ramdaspeth,https://www.google.com/search?gs_ssp=eJzj4tVP1...
29,Theka Coffee,Beverages,100-150,Bajaj Nagar,https://www.google.com/search?q=theka%20coffee...
30,MBA Chaiwala,Beverages,100-150,Bajaj Nagar,https://www.google.com/search?q=mba+chai+wala+...
33,The Fuel Station,Beverages,150-300,"Shankar Nagar, Hingna T-Point",https://www.google.com/search?q=fuel+station+n...
34,The Fuel Headquarters,Beverages,150-300,"Bajaj Nagar, Wardhaman Nagar",https://www.google.com/search?q=fuel+headquart...
38,Drunken Monkey,Beverages,150-300,"Dharampeth, Laxmi Nagar, Pratap Nagar, Trimurt...",https://www.google.com/search?q=drunken+monkey...
42,ThirtySixty,Beverages,300-600,Medical Square,https://www.google.com/search?gs_ssp=eJzj4tVP1...
49,Food Courtyard,Beverages,150-300,Laxmi Nagar,https://www.google.com/search?q=food+courtyard...